DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS petsitters CASCADE;

CREATE TABLE IF NOT EXISTS users (
  username VARCHAR(64) PRIMARY KEY,
  email VARCHAR(64) UNIQUE NOT NULL,
  password VARCHAR(64) NOT NULL);
 
CREATE TABLE IF NOT EXISTS petsitters (
  username VARCHAR(64) PRIMARY KEY REFERENCES users (username) ON DELETE CASCADE,
  startDate DATE,
  endDate DATE,
  price NUMERIC NOT NULL,
  dog BOOLEAN NOT NULL DEFAULT FALSE,
  cat BOOLEAN NOT NULL DEFAULT FALSE,
  petBoarding BOOLEAN NOT NULL DEFAULT FALSE,
  dogWalking BOOLEAN NOT NULL DEFAULT FALSE,
  petGrooming BOOLEAN NOT NULL DEFAULT FALSE,
  petDaycare BOOLEAN NOT NULL DEFAULT FALSE,
  petSitting BOOLEAN NOT NULL DEFAULT FALSE,
  petTaxi BOOLEAN NOT NULL DEFAULT FALSE);

SELECT * FROM users;
SELECT * FROM petsitters;